spring.application.name=biblioteca
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
server.port=${SERVER_PORT}
